"""initial_schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-03-21 22:42:18.372460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('google_place_id', sa.String(length=256), nullable=True),
    sa.Column('primary_category', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poi_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('routing_cache_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin_hash', sa.String(length=64), nullable=False),
    sa.Column('destination_hash', sa.String(length=64), nullable=False),
    sa.Column('plan_day_type', sa.String(length=16), nullable=False),
    sa.Column('departure_bucket', sa.String(length=32), nullable=False),
    sa.Column('routing_preference', sa.String(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routing_cache_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routing_cache_entry_destination_hash'), ['destination_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_routing_cache_entry_origin_hash'), ['origin_hash'], unique=False)

    op.create_table('routing_request_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_kind', sa.String(length=32), nullable=False),
    sa.Column('element_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lng', sa.Float(), nullable=False),
    sa.Column('origin_label', sa.String(length=256), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lng', sa.Float(), nullable=False),
    sa.Column('dest_label', sa.String(length=256), nullable=False),
    sa.Column('departure_window_start_min', sa.Integer(), nullable=False),
    sa.Column('departure_window_end_min', sa.Integer(), nullable=False),
    sa.Column('return_deadline_min', sa.Integer(), nullable=False),
    sa.Column('weather_mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poi_dependency_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('if_visit_poi_id', sa.Integer(), nullable=False),
    sa.Column('require_poi_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['if_visit_poi_id'], ['poi_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['require_poi_id'], ['poi_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poi_opening_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('open_minute', sa.Integer(), nullable=False),
    sa.Column('close_minute', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.String(length=10), nullable=True),
    sa.Column('valid_to', sa.String(length=10), nullable=True),
    sa.Column('holiday_note', sa.String(length=256), nullable=True),
    sa.Column('last_admission_minute', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poi_planning_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('stay_min_minutes', sa.Integer(), nullable=False),
    sa.Column('stay_max_minutes', sa.Integer(), nullable=False),
    sa.Column('meal_window_start_min', sa.Integer(), nullable=True),
    sa.Column('meal_window_end_min', sa.Integer(), nullable=True),
    sa.Column('is_indoor', sa.Boolean(), nullable=False),
    sa.Column('sunset_score', sa.Integer(), nullable=False),
    sa.Column('scenic_score', sa.Integer(), nullable=False),
    sa.Column('relax_score', sa.Integer(), nullable=False),
    sa.Column('parking_note', sa.Text(), nullable=True),
    sa.Column('difficulty_note', sa.Text(), nullable=True),
    sa.Column('utility_default', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poi_id')
    )
    op.create_table('poi_source_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poi_tag_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['poi_tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poi_id', 'tag_id', name='uq_poi_tag')
    )
    op.create_table('solver_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('solve_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('solve_ms', sa.Integer(), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('infeasible_reason', sa.String(length=256), nullable=True),
    sa.Column('route_summary_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('must_visit', sa.Boolean(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('locked_in', sa.Boolean(), nullable=False),
    sa.Column('locked_out', sa.Boolean(), nullable=False),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('utility_override', sa.Integer(), nullable=True),
    sa.Column('candidate_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi_master.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_execution_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_preference_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('driving_penalty_weight', sa.Float(), nullable=False),
    sa.Column('max_continuous_drive_minutes', sa.Integer(), nullable=False),
    sa.Column('preferred_lunch_tags', sa.JSON(), nullable=False),
    sa.Column('preferred_dinner_tags', sa.JSON(), nullable=False),
    sa.Column('must_have_cafe', sa.Boolean(), nullable=False),
    sa.Column('budget_band', sa.String(length=32), nullable=True),
    sa.Column('pace_style', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id')
    )
    op.create_table('planned_stop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solver_run_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('poi_id', sa.Integer(), nullable=True),
    sa.Column('node_kind', sa.String(length=16), nullable=False),
    sa.Column('arrival_min', sa.Integer(), nullable=True),
    sa.Column('departure_min', sa.Integer(), nullable=True),
    sa.Column('stay_min', sa.Integer(), nullable=True),
    sa.Column('leg_from_prev_min', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi_master.id'], ),
    sa.ForeignKeyConstraint(['solver_run_id'], ['solver_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_stop')
    op.drop_table('trip_preference_profile')
    op.drop_table('trip_execution_event')
    op.drop_table('trip_candidate')
    op.drop_table('solver_run')
    op.drop_table('poi_tag_link')
    op.drop_table('poi_source_snapshot')
    op.drop_table('poi_planning_profile')
    op.drop_table('poi_opening_rule')
    op.drop_table('poi_dependency_rule')
    op.drop_table('trip_plan')
    op.drop_table('routing_request_log')
    with op.batch_alter_table('routing_cache_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routing_cache_entry_origin_hash'))
        batch_op.drop_index(batch_op.f('ix_routing_cache_entry_destination_hash'))

    op.drop_table('routing_cache_entry')
    op.drop_table('poi_tag')
    op.drop_table('poi_master')
    # ### end Alembic commands ###
